---
name: monster-ui-application-csv-onboarding
base_branch: 'origin/5.2'
exposure: private
metapackage:
  - name: meta-monster-ui
    branch: '5.2'
    package: monster-ui-application-csv-onboarding
    type: required
base_core: monster-ui
template: monster-ui-application.spec.tmpl
package:
  centos7:
    name: monster-ui-application-csv-onboarding
    app_name: csv-onboarding
    license: "MPL 2.0"
    group: Productivity/Telephony
    url: http://www.2600hz.org/
    vendor: 2600Hz
